spring.application.name=devguard
spring.datasource.url=jdbc:mysql://localhost:3306/devguard
spring.datasource.username=root
spring.datasource.password=Pranathivanga@13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
